### ISSUE TITLE
Interaction with object references from primitives

### ISSUE THREAD

**Issue by acutmore** [syg/proposal-structs#10]
A curiosity more than an 'issue'.  The [Record&Tuple proposal](https://github.com/tc39/proposal-record-tuple) could end up introducing primitives that contain references to objects.

What do we think should happen when these interact with shared structs?

```js
shared struct class Structy {
  x;
  constructor(x) {
    this.x = #[1, 2, 3, Box({})];
  }
}
```

Would it immediately throw as this isn't _deeply_ primitive?

EDIT: clarify `shared struct`

**Comment by ljharb** [comment]
@acutmore tbf it's still new even if there's a dozen stage 1 proposals that add it :-p
